export const routes = {
   
    applicant: {
        applicant_register: 'employee/applicant',
        applicant_login: 'employee/applicant/login',
        create_password : 'employee/applicant/password',
        step1: 'employee/applicant/step/1',
        step2: 'employee/applicant/step/2',
        step3: 'employee/applicant/step/3',
        step3Forms: 'employee/applicant/form/',
        submitStep4: 'employee/applicant/step/4',
        retreiveForm: '/employee/applicant/retreiveform/'
    },
    employee: {
        employee_login: 'employee/employee/login',
        getProfilePic: 'employee/employee/profile_pic',
        setProfilePic: 'employee/employee/profile_pic',
        get_employee_all_certificates : 'employee/certificate/employee/',
        get_employee_list : 'employee/hr/employee',
        get_department_list: 'employee/department',
        get_ticket_type_list: 'employee/ticket/type',
        get_ticket_category_by_type: 'employee/ticket/type/category/',
        create_ticket: 'employee/ticket',
        department_contact_list: 'employee/departmentContact/',
        job_category_list: 'employee/jobCategory',
        site_list: 'employee/location',
        create_test_event: 'employee/testEvent/1',
        get_test_event_list: 'employee/testEvent',
        get_test_event_by_id:'employee/testEvent/',
        get_rules_list:'employee/testEventRule/rules',
        create_test_event_rule:'employee/testEventRule',
        view_test_event_rule:'employee/testEventRuleResult/',
        departments_list: 'employee/department/',
        all_subdepartments: 'employee/department/sub',
        add_certificate: 'employee/certificate',
        update_certificate: 'employee/certificate/',
        get_crew_user_list: 'employee/employee/crew',
        get_assisting_member_list: 'employee/employee/assising'
    },
    it :{
        list_it_request : 'employee/ITRequest',
        get_it_request  : 'employee/ITRequest/',
        update_it_request  : 'employee/ITRequest/',
    },
    hr:{
        get_applicant: 'employee/hr/applicant',
        get_applicant_by_id : 'employee/hr/applicant/',
        get_applicants_by_name: 'employee/hr/search/employee',
        step1 : 'employee/hr/step/0/approve',
        step2 : 'employee/hr/step/1/approve',
        reject : 'employee/hr/step/reject',
        get_tickets_and_allerts: 'employee/ticket',
        list_tickets_and_alerts_by_category: 'employee/ticket/category/',
        get_ticket_by_id: 'employee/ticket/',
        update_tickets : 'employee/ticket/',
        get_employee_by_id : 'employee/hr/employee/',
        update_employee_address :'employee/hr/employee',
        //files
        additional_files_uplaod : 'employee/hr/add_files/',
        get_certificate: 'employee/certificate/employee/',
        get_certificate_type: 'employee/certificate/type',
        update_position: 'employee/hr/employee/position',
        update_pay: 'employee/hr/employee/pay',
        terminate: 'employee/hr/employee/terminate',
        // dropdowns 
        position_level : 'employee/level/',
        get_job_categories : 'employee/jobCategory',
        department : 'employee/department',
        location : '/employee/location',
        paytype : 'employee/payType',
        subDepartment : 'employee/department/subDepartment/',
    },
    broadcast:{
        create: 'employee/broadcastMessage/',
        getAllSend: 'employee/broadcastMessage/send',
        getAll: 'employee/broadcastMessage/recieve',
    },
    checkride:{
        create:'/employee/checkRide/',
        checkride_table:'employee/checkRide'
    }
}
